# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='app_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
